//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public int Id_Administrador { get; set; }
        public int Id_Usr_Admin { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
