//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADSCRIPTO
    {
        public int Id_Adscripto { get; set; }
        public int Id_Usr_Adscripto { get; set; }
        public int Turno_Adscripto { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual TURNO TURNO { get; set; }
    }
}
