//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public int Id_Alumno { get; set; }
        public int Id_Usr_Alumno { get; set; }
        public int Grupo_Usr { get; set; }
    
        public virtual GRUPO GRUPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
