//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCUESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCUESTA()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
        }
    
        public int Id_Encuesta { get; set; }
        public int Creador_Encuesta { get; set; }
        public System.DateTime Fecha_Encuesta { get; set; }
        public System.DateTime Fecha_Fin_Encuesta { get; set; }
        public string Titulo_Encuesta { get; set; }
        public string Descripcion_Encuesta { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
    }
}
