//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO()
        {
            this.ALUMNO = new HashSet<ALUMNO>();
            this.HORARIO = new HashSet<HORARIO>();
            this.NOTIFICACION_DESTINATARIO = new HashSet<NOTIFICACION_DESTINATARIO>();
            this.PRUEBA = new HashSet<PRUEBA>();
            this.TAREA_GRUPO = new HashSet<TAREA_GRUPO>();
        }
    
        public int Id_Grupo { get; set; }
        public int Grado_Grupo { get; set; }
        public int Orientacion_Grupo { get; set; }
        public int Numero_Grupo { get; set; }
        public Nullable<int> Turno_Grupo { get; set; }
        public int Anio_grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUMNO> ALUMNO { get; set; }
        public virtual ORIENTACION ORIENTACION { get; set; }
        public virtual TURNO TURNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_DESTINATARIO> NOTIFICACION_DESTINATARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA_GRUPO> TAREA_GRUPO { get; set; }
    }
}
