//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTIFICACION()
        {
            this.NOTIFICACION_DESTINATARIO = new HashSet<NOTIFICACION_DESTINATARIO>();
        }
    
        public int Id_Notificacion { get; set; }
        public string Destino_Notificacion { get; set; }
        public System.DateTime Fecha_Notificacion { get; set; }
        public string Titulo_Notificacion { get; set; }
        public string Mensaje_Notificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_DESTINATARIO> NOTIFICACION_DESTINATARIO { get; set; }
    }
}
