//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICACION_DESTINATARIO
    {
        public int Id_ND { get; set; }
        public int Id_Destinatario { get; set; }
        public Nullable<int> Grupo_Actual_Usr { get; set; }
        public System.DateTime Fecha_Envio { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
    
        public virtual GRUPO GRUPO { get; set; }
        public virtual NOTIFICACION NOTIFICACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
