//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPCION_PREGUNTA()
        {
            this.RESPUESTA_ENCUESTA = new HashSet<RESPUESTA_ENCUESTA>();
        }
    
        public int Id_OP { get; set; }
        public int Id_Pregunta_OP { get; set; }
        public string Texto_OP { get; set; }
    
        public virtual PREGUNTA PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTA_ENCUESTA> RESPUESTA_ENCUESTA { get; set; }
    }
}
