//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PONDERACION
    {
        public int Id_Nodo_Actual { get; set; }
        public int Id_Nodo_Adyacente { get; set; }
        public int Ponderacion1 { get; set; }
    
        public virtual NODO NODO { get; set; }
        public virtual NODO NODO1 { get; set; }
    }
}
