//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTA()
        {
            this.OPCION_PREGUNTA = new HashSet<OPCION_PREGUNTA>();
            this.RESPUESTA_ENCUESTA = new HashSet<RESPUESTA_ENCUESTA>();
        }
    
        public int Id_Pregunta { get; set; }
        public int Id_Encuesta_Pregunta { get; set; }
        public string Texto_Pregunta { get; set; }
    
        public virtual ENCUESTA ENCUESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCION_PREGUNTA> OPCION_PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTA_ENCUESTA> RESPUESTA_ENCUESTA { get; set; }
    }
}
