//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRUEBA
    {
        public int Id_Prueba { get; set; }
        public string Tipo_Prueba { get; set; }
        public int Id_Materia_Prueba { get; set; }
        public int Id_Grupo_Prueba { get; set; }
        public int Id_Docente_Prueba { get; set; }
        public System.DateTime Fecha_Prueba { get; set; }
        public int Hora_Inicio_Prueba { get; set; }
        public int Hora_Fin_Prueba { get; set; }
        public string Temas_Prueba { get; set; }
    
        public virtual DOCENTE DOCENTE { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        public virtual HORA_TURNO HORA_TURNO { get; set; }
        public virtual HORA_TURNO HORA_TURNO1 { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
