//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPUESTA_ENCUESTA
    {
        public int Id_Usuario_Encuestado { get; set; }
        public int Id_Pregunta_Respondida { get; set; }
        public int Id_Respuesta { get; set; }
        public int Id_Respusta_Encuesta { get; set; }
    
        public virtual OPCION_PREGUNTA OPCION_PREGUNTA { get; set; }
        public virtual PREGUNTA PREGUNTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
