//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SigmaContext : DbContext
    {
        public SigmaContext()
            : base("name=SigmaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<ADSCRIPTO> ADSCRIPTO { get; set; }
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<BEACON> BEACON { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<DOCENTE> DOCENTE { get; set; }
        public virtual DbSet<ENCUESTA> ENCUESTA { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<HORA> HORA { get; set; }
        public virtual DbSet<HORA_TURNO> HORA_TURNO { get; set; }
        public virtual DbSet<HORARIO> HORARIO { get; set; }
        public virtual DbSet<MATERIA> MATERIA { get; set; }
        public virtual DbSet<NODO> NODO { get; set; }
        public virtual DbSet<NOTIFICACION> NOTIFICACION { get; set; }
        public virtual DbSet<NOTIFICACION_DESTINATARIO> NOTIFICACION_DESTINATARIO { get; set; }
        public virtual DbSet<OPCION_PREGUNTA> OPCION_PREGUNTA { get; set; }
        public virtual DbSet<ORIENTACION> ORIENTACION { get; set; }
        public virtual DbSet<PONDERACION> PONDERACION { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTA { get; set; }
        public virtual DbSet<PRUEBA> PRUEBA { get; set; }
        public virtual DbSet<TAREA> TAREA { get; set; }
        public virtual DbSet<TAREA_GRUPO> TAREA_GRUPO { get; set; }
        public virtual DbSet<TURNO> TURNO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<RESPUESTA_ENCUESTA> RESPUESTA_ENCUESTA { get; set; }
        public virtual DbSet<TAREA_ADJUNTO> TAREA_ADJUNTO { get; set; }
    
        public virtual int PR_Ingresar_Usuario(string pCedula_Usr, string pPassword, string pCelular_Usr, string pToken_Usr, string pNombre_Usr, string pApellido_Usr, ObjectParameter mensajeRespuesta)
        {
            var pCedula_UsrParameter = pCedula_Usr != null ?
                new ObjectParameter("pCedula_Usr", pCedula_Usr) :
                new ObjectParameter("pCedula_Usr", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pCelular_UsrParameter = pCelular_Usr != null ?
                new ObjectParameter("pCelular_Usr", pCelular_Usr) :
                new ObjectParameter("pCelular_Usr", typeof(string));
    
            var pToken_UsrParameter = pToken_Usr != null ?
                new ObjectParameter("pToken_Usr", pToken_Usr) :
                new ObjectParameter("pToken_Usr", typeof(string));
    
            var pNombre_UsrParameter = pNombre_Usr != null ?
                new ObjectParameter("pNombre_Usr", pNombre_Usr) :
                new ObjectParameter("pNombre_Usr", typeof(string));
    
            var pApellido_UsrParameter = pApellido_Usr != null ?
                new ObjectParameter("pApellido_Usr", pApellido_Usr) :
                new ObjectParameter("pApellido_Usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Ingresar_Usuario", pCedula_UsrParameter, pPasswordParameter, pCelular_UsrParameter, pToken_UsrParameter, pNombre_UsrParameter, pApellido_UsrParameter, mensajeRespuesta);
        }
    
        public virtual int PR_Login(string pCedula, string pPassword, ObjectParameter mensajeRespuesta)
        {
            var pCedulaParameter = pCedula != null ?
                new ObjectParameter("pCedula", pCedula) :
                new ObjectParameter("pCedula", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Login", pCedulaParameter, pPasswordParameter, mensajeRespuesta);
        }
    
        public virtual ObjectResult<string> CreateUser(string pCedula_Usr, string pPassword, string pCelular_Usr, string pToken_Usr, string pNombre_Usr, string pApellido_Usr, ObjectParameter mensajeRespuesta)
        {
            var pCedula_UsrParameter = pCedula_Usr != null ?
                new ObjectParameter("pCedula_Usr", pCedula_Usr) :
                new ObjectParameter("pCedula_Usr", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pCelular_UsrParameter = pCelular_Usr != null ?
                new ObjectParameter("pCelular_Usr", pCelular_Usr) :
                new ObjectParameter("pCelular_Usr", typeof(string));
    
            var pToken_UsrParameter = pToken_Usr != null ?
                new ObjectParameter("pToken_Usr", pToken_Usr) :
                new ObjectParameter("pToken_Usr", typeof(string));
    
            var pNombre_UsrParameter = pNombre_Usr != null ?
                new ObjectParameter("pNombre_Usr", pNombre_Usr) :
                new ObjectParameter("pNombre_Usr", typeof(string));
    
            var pApellido_UsrParameter = pApellido_Usr != null ?
                new ObjectParameter("pApellido_Usr", pApellido_Usr) :
                new ObjectParameter("pApellido_Usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CreateUser", pCedula_UsrParameter, pPasswordParameter, pCelular_UsrParameter, pToken_UsrParameter, pNombre_UsrParameter, pApellido_UsrParameter, mensajeRespuesta);
        }
    
        public virtual int PR_Ingresar_Orientacion(string nombre_Orientacion, ObjectParameter mensajeRespuesta)
        {
            var nombre_OrientacionParameter = nombre_Orientacion != null ?
                new ObjectParameter("Nombre_Orientacion", nombre_Orientacion) :
                new ObjectParameter("Nombre_Orientacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Ingresar_Orientacion", nombre_OrientacionParameter, mensajeRespuesta);
        }
    }
}
