//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA_ADJUNTO
    {
        public Nullable<int> Id_Tarea_TA { get; set; }
        public string Url_Adjunto { get; set; }
    
        public virtual TAREA TAREA { get; set; }
    }
}
