//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.TAREA_ADJUNTO = new HashSet<TAREA_ADJUNTO>();
            this.TAREA_GRUPO = new HashSet<TAREA_GRUPO>();
        }
    
        public int Id_Tarea { get; set; }
        public int Id_Docente { get; set; }
        public Nullable<int> Id_Materia_Tarea { get; set; }
        public string Contenido_Tarea { get; set; }
    
        public virtual DOCENTE DOCENTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA_ADJUNTO> TAREA_ADJUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA_GRUPO> TAREA_GRUPO { get; set; }
    }
}
