//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA_GRUPO
    {
        public int Id_TG { get; set; }
        public int Id_Grupo_TG { get; set; }
        public System.DateTime Fecha_TG { get; set; }
        public System.DateTime Fecha_Entrega_TG { get; set; }
    
        public virtual GRUPO GRUPO { get; set; }
        public virtual TAREA TAREA { get; set; }
    }
}
